### PR TITLE
Removing vague line that covers in person activity outside of the Slack

### PR DESCRIPTION
**Pull request by campbecf**
This line might make sense within the context of a specific event (RubyConf, Code Mash, etc..) but I feel it is overly broad for a community in which we live day to day lives outside of work.

This clause potentially has enforcement issues over minor offenses outside of Slack and outside of work. Person A says Person B did X. How do we prove this? How do we verify this? We should not turn our moderators into judges.

The line: `Intimidation or harassment (online or in-person). Please read the Citizen Code of Conduct for how we interpret harassment.`

Already covers intimidation (threats etc..) as well as harassment in person.

### CODE REVIEW

**Comment by jakeboyles** [comment]
+1

**Comment by howeszy** [comment]
👍

**Comment by pitchinnate** [comment]
👍

**Comment by zarahzachz** [comment]
> has the potential to adversely affect the safety and well-being of community members.

That seems pretty clear to me. Basically don't do anything that hurts someone else?

**Comment by campbecf** [comment]
@zarahzachz I feel like that is already covered under Intimidation or harassment below. I would support rewording the statement to specifically cover safety issues. The statement itself should be simplified if we decide to keep it. The use of `unacceptable behavior` at the start could mean anything.

`well-being` is also a little vague `the state of being comfortable, healthy, or happy.`

If I fire an employee have I just diminished the well-being of someone? What if I was asked for a recommendation and gave a negative review of Contractor X? What if I spoke about some bad work Contractor X did for me in a bar/restaurant and a friend overheard and told Contractor X? 

I would be okay with:

```
This code and related procedures also apply to behavior occurring outside the scope of community activities that has the potential to adversely affect the safety of community members.
```

That said we aren't the police or a college campus. Safety issues should ideally be handled outside the scope of a Slack chat room.

**Comment by geofflane** [comment]
-1 I disagree with removing this. If someone in this group is harassing or threatening, or generally being a jerk to someone in the real world that make them not want to associate with that person, then applying that to the online portion of the community seems reasonable to me.

**Comment by geofflane** [comment]
For more reasoning on why this is in the CoC, see: https://www.ashedryden.com/blog/codes-of-conduct-101-faq#cocfaqnonofficial

**Comment by campbecf** [comment]
@geofflane That is already covered in this document by:

```
Intimidation or harassment (online or in-person). Please read the Citizen Code of Conduct for how we interpret harassment.
```
and
```
Violence, threats of violence or violent language.
```

**Comment by campbecf** [comment]
@geofflane That blog post is about a conference, which I think the original Code of Conduct is probably fine in that scope. The Code of Conduct is not for a conference. It is for a permanent community of individuals that live local to one another. The chances of accidentally bumping into or overhearing a member of Cincy Tech Slack is fairly high. Especially at lunch or downtown.

Nobody is advocating that we allow violent or threatening people to remain as part of the community. The document covers that without this initial clause.

**Comment by geofflane** [comment]
@campbecf I think it just makes it clear that the community is broader than Slack, as you say. Slack is one vehicle, among many, where people in the Cincinnati Tech community interact. The goal of the CoC is to make the community welcoming to as many people as possible. The goal is NOT to remove people from the community. But there is a mechanism for removal if that's necessary.

**Comment by campbecf** [comment]
I would prefer to use #9 instead of making these changes.

**Comment by campbecf** [comment]
Closing this in favor of using the Geek Feminism Code of Conduct based on our discussions on Slack.

**Pull request closed without merging**
